import Foundation

private struct QueryInput {
  let propertyName: String
  let path: String
}

private enum GeneratorError: Error, CustomStringConvertible {
  case invalidArguments

  var description: String {
    switch self {
    case .invalidArguments:
      return
        "usage: EmbedHighlightQueriesTool <output> <json> <markdown-block> <markdown-inline> <sema>"
    }
  }
}

private func byteArrayLiteral(for data: Data) -> String {
  let bytes = Array(data)
  guard !bytes.isEmpty else { return "[]" }

  var lines: [String] = []
  for start in stride(from: 0, to: bytes.count, by: 16) {
    let end = min(start + 16, bytes.count)
    let values = bytes[start..<end].map(String.init).joined(separator: ", ")
    lines.append("      \(values),")
  }
  return "[\n\(lines.joined(separator: "\n"))\n    ]"
}

private func run() throws {
  let arguments = CommandLine.arguments
  guard arguments.count == 6 else { throw GeneratorError.invalidArguments }

  let outputPath = arguments[1]
  let inputs = [
    QueryInput(propertyName: "json", path: arguments[2]),
    QueryInput(propertyName: "markdownBlock", path: arguments[3]),
    QueryInput(propertyName: "markdownInline", path: arguments[4]),
    QueryInput(propertyName: "sema", path: arguments[5]),
  ]

  var declarations: [String] = []
  for input in inputs {
    let data = try Data(contentsOf: URL(fileURLWithPath: input.path))
    declarations.append(
      "  static let \(input.propertyName) = Data(\(byteArrayLiteral(for: data)))"
    )
  }

  let generated = """
    // Generated by EmbedHighlightQueriesTool. Do not edit.
    import Foundation

    enum EmbeddedHighlightQueries {
    \(declarations.joined(separator: "\n"))
    }

    """
  try Data(generated.utf8).write(to: URL(fileURLWithPath: outputPath), options: .atomic)
}

do {
  try run()
} catch {
  FileHandle.standardError.write(Data("error: \(error)\n".utf8))
  exit(1)
}
