#!/usr/bin/env python3
"""Generate the length-preserving Unicode simple case-fold table for Zest."""

from __future__ import annotations

import hashlib
from pathlib import Path
from urllib.request import urlopen


UNICODE_VERSION = "17.0.0"
SOURCE_URL = f"https://www.unicode.org/Public/{UNICODE_VERSION}/ucd/CaseFolding.txt"
SOURCE_SHA256 = "ff8d8fefbf123574205085d6714c36149eb946d717a0c585c27f0f4ef58c4183"
OUTPUT = Path(__file__).resolve().parents[1] / "src/core/casefold_data.zig"


def utf8_len(codepoint: int) -> int:
    if codepoint < 0x80:
        return 1
    if codepoint < 0x800:
        return 2
    if codepoint < 0x10000:
        return 3
    return 4


def read_mappings(source: bytes) -> list[tuple[int, int]]:
    mappings: dict[int, int] = {}
    for raw_line in source.decode("utf-8").splitlines():
        data = raw_line.split("#", 1)[0].strip()
        if not data:
            continue
        fields = [part.strip() for part in data.split(";")]
        if len(fields) < 3:
            raise ValueError(f"malformed CaseFolding.txt row: {raw_line}")
        source_hex, status, target_hex = fields[:3]
        # Unicode specifies C + S as the simple case-fold mapping. F can grow
        # strings, and T is the opt-in Turkic variant, so neither fits Zest's
        # byte-parallel folded-name blob.
        if status not in {"C", "S"}:
            continue
        targets = target_hex.split()
        if len(targets) != 1:
            raise ValueError(f"simple mapping has {len(targets)} targets: {raw_line}")
        source_cp = int(source_hex, 16)
        target_cp = int(targets[0], 16)
        if utf8_len(source_cp) != utf8_len(target_cp):
            continue
        if source_cp in mappings:
            raise ValueError(f"duplicate simple mapping for U+{source_cp:04X}")
        mappings[source_cp] = target_cp
    return sorted(mappings.items())


def render(mappings: list[tuple[int, int]]) -> str:
    rows = "\n".join(
        f"    .{{ .source = 0x{source:04X}, .target = 0x{target:04X} }},"
        for source, target in mappings
    )
    return f"""//! Generated by Tools/generate_casefold.py; do not edit by hand.
//! Source: {SOURCE_URL}
//! Unicode terms: https://www.unicode.org/terms_of_use.html
//!
//! Only Unicode simple mappings (status C or S) whose source and target have
//! the same UTF-8 byte length are retained. That invariant lets the folded
//! filename blob share the original blob's offset and length columns.

pub const unicode_version = "{UNICODE_VERSION}";

pub const Mapping = struct {{
    source: u21,
    target: u21,
}};

pub const mappings = [_]Mapping{{
{rows}
}};
"""


def main() -> None:
    with urlopen(SOURCE_URL, timeout=30) as response:
        source = response.read()
    digest = hashlib.sha256(source).hexdigest()
    if digest != SOURCE_SHA256:
        raise RuntimeError(
            f"unexpected CaseFolding.txt checksum: expected {SOURCE_SHA256}, got {digest}"
        )
    mappings = read_mappings(source)
    OUTPUT.write_text(render(mappings), encoding="utf-8")
    print(f"wrote {len(mappings)} mappings to {OUTPUT}")


if __name__ == "__main__":
    main()
